# Generated by Django 2.2.9 on 2020-02-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_drop_all_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fh4track',
            options={'verbose_name': 'FH4 Track'},
        ),
    ]
