# Generated by Django 2.2.9 on 2020-02-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20200203_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fh4track',
            options={'verbose_name': 'FH4 Event'},
        ),
        migrations.AlterField(
            model_name='fh4track',
            name='time_of_day',
            field=models.CharField(choices=[('Da', 'Dawn'), ('Su', 'Sunrise'), ('Mo', 'Morning'), ('No', 'Noon'), ('Af', 'Afternoon'), ('Se', 'Sunset'), ('Du', 'Dusk'), ('Ni', 'Night'), ('??', 'Current')], default='No', help_text='When this race takes place', max_length=2, verbose_name='Time of day'),
        ),
        migrations.AlterField(
            model_name='fh4track',
            name='weather',
            field=models.CharField(choices=[('S ', 'Sunny'), ('Sr', 'Sunny (wet)'), ('C ', 'Cloudy'), ('Cr', 'Cloudy (wet)'), ('O ', 'Overcast'), ('Lr', 'Light rain/snow'), ('Hr', 'Heavy rain/snow'), ('FB', 'Foggy/Blizzard'), ('??', 'Current')], default='S ', help_text='What kind of weather will be present at the event', max_length=30),
        ),
    ]
