# Generated by Django 2.2.9 on 2020-02-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_auto_20200207_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fh4overviewpage',
            options={'verbose_name': 'FH4 All Events Overview'},
        ),
    ]
