# Generated by Django 2.2.9 on 2020-02-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('overview', '0004_auto_20200207_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='FH4Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this championship', max_length=50, verbose_name='Championship name')),
                ('description', models.CharField(blank=True, default='', help_text='A nice little description about this championship', max_length=250, verbose_name='Description')),
                ('type', models.CharField(choices=[('r', 'Sprint'), ('R', 'Circuit'), ('d', 'Rally'), ('D', 'Dirt Track'), ('c', 'CC Sprint'), ('C', 'CC Circuit')], help_text='What kind of championship this is', max_length=1, verbose_name='Championship type')),
                ('prize_money', models.IntegerField(default=0, help_text='The pize money assigned to this championship', verbose_name='Prize money')),
                ('further_prize', models.CharField(blank=True, help_text='An additional prize given to the winner of the championship', max_length=200, null=True, verbose_name='Additional prize')),
                ('championship_image', models.ForeignKey(help_text='A pretty image that represents teh championship, instead of just some plain old text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Championship image')),
                ('tracks', models.ManyToManyField(to='overview.FH4Track')),
            ],
        ),
    ]
