# Generated by Django 2.2.9 on 2020-02-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_fh4championship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fh4championship',
            options={'verbose_name': 'FH4 Championship'},
        ),
        migrations.AlterField(
            model_name='fh4championship',
            name='championship_image',
            field=models.ForeignKey(blank=True, help_text='A pretty image that represents teh championship, instead of just some plain old text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Championship image'),
        ),
    ]
