# Generated by Django 2.2.9 on 2020-02-08 16:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('overview', '0006_auto_20200208_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='FH4ChampOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, help_text='And intro text to give readers some context', null=True, verbose_name='Intro text')),
            ],
            options={
                'verbose_name': 'FH4 All Events Overview',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='fh4overviewpage',
            options={'verbose_name': 'FH4 All Championships Overview'},
        ),
        migrations.RenameField(
            model_name='fh4championship',
            old_name='tracks',
            new_name='events',
        ),
    ]
