# Generated by Django 2.2.9 on 2020-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_auto_20200208_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='fh4tune',
            name='car',
            field=models.CharField(help_text='The car this tune was made for', max_length=150, null=True, verbose_name='Car name'),
        ),
    ]
