# Generated by Django 2.2.9 on 2020-02-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0009_fh4tune_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fh4tune',
            name='drivetrain',
            field=models.CharField(choices=[('F', 'FF'), ('h', 'FR'), ('H', 'RR'), ('M', 'MR'), ('A', 'AWD')], help_text='Where the engine lies and what wheels are driven by it', max_length=1, null=True, verbose_name='Drivetrain'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='intake',
            field=models.CharField(choices=[('/', 'Naturally Aspirated'), ('S', 'Supercharger'), ('C', 'Centrifugal Supercharger'), ('t', 'Single Turbo'), ('T', 'Two Turbos')], help_text='If/How extra air is forced into the engine', max_length=1, null=True, verbose_name='Intake type'),
        ),
    ]
