# Generated by Django 2.2.9 on 2020-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_auto_20200208_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fh4tune',
            name='pi',
            field=models.IntegerField(help_text='The performance index of this tune', verbose_name='Performance Index'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='rating_accel',
            field=models.IntegerField(default=0.0, help_text='The Forza-internal accelearation rating', verbose_name='Acceleration handling'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='rating_brakes',
            field=models.IntegerField(default=0.0, help_text='The Forza-internal brakes rating', verbose_name='Brakes rating'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='rating_handling',
            field=models.IntegerField(default=0.0, help_text='The Forza-internal handling rating', verbose_name='Handling rating'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='rating_speed',
            field=models.IntegerField(default=0.0, help_text='The Forza-internal speed rating', verbose_name='Speed rating'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='rating_start',
            field=models.IntegerField(default=0.0, help_text='The Forza-internal start rating', verbose_name='Start rating'),
        ),
    ]
