# Generated by Django 2.2.9 on 2020-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0011_auto_20200208_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fh4championship',
            name='type',
            field=models.CharField(choices=[('r', 'Sprint'), ('R', 'Rundkurs'), ('d', 'Rallye'), ('D', 'Dirt Track'), ('c', 'Offroad-Sprint'), ('C', 'Offroadkurs'), ('A', 'Asphalt'), ('E', 'Alle Straßenbeläge'), ('G', 'Schotter'), ('€', 'Offroad'), ('S', 'Straßenszene')], help_text='What kind of championship this is', max_length=1, verbose_name='Championship type'),
        ),
        migrations.AlterField(
            model_name='fh4route',
            name='type',
            field=models.CharField(choices=[('r', 'Sprint'), ('R', 'Rundkurs'), ('d', 'Rallye'), ('D', 'Dirt Track'), ('c', 'Offroad-Sprint'), ('C', 'Offroadkurs')], help_text='What kind of race this is', max_length=1, verbose_name='Track type'),
        ),
        migrations.AlterField(
            model_name='fh4track',
            name='car_power',
            field=models.CharField(choices=[('X', 'X Klasse'), ('2', 'S2 Klasse'), ('1', 'S1 Klasse'), ('A', 'A Klasse'), ('B', 'B Klasse'), ('C', 'C Klasse'), ('D', 'D Klasse'), ('-', 'Unbeschränkt')], default='-', help_text='The recommended/restricted car class for this event', max_length=1, null=True, verbose_name='Power limit'),
        ),
        migrations.AlterField(
            model_name='fh4track',
            name='season',
            field=models.CharField(choices=[('W', 'Winter'), ('F', 'Frühling'), ('S', 'Sommer'), ('H', 'Herbst')], help_text='In which season this event takes place', max_length=1, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='fh4track',
            name='time_of_day',
            field=models.CharField(choices=[('Da', 'Morgengrauen'), ('Su', 'Sonnenaufgang'), ('Mo', 'Morgen'), ('No', 'Mittag'), ('Af', 'Nachmittag'), ('Se', 'Sonnenuntergang'), ('Du', 'Abend'), ('Ni', 'Nacht'), ('??', 'Aktuell')], default='No', help_text='When this race takes place', max_length=2, verbose_name='Time of day'),
        ),
        migrations.AlterField(
            model_name='fh4track',
            name='weather',
            field=models.CharField(choices=[('S ', 'Heiter'), ('Sr', 'Heiter (nass)'), ('C ', 'Wolkig'), ('Cr', 'Wolkig (nass)'), ('O ', 'Bewölkt'), ('Lr', 'Leichter Regen'), ('Ls', 'Leichter Schneefall'), ('Hr', 'Starker Regen'), ('Hs', 'Starker Schneefall'), ('FB', 'Nebel'), ('Bl', 'Blizzard'), ('??', 'Aktuell')], default='S ', help_text='What kind of weather will be present at the event', max_length=30),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='intake',
            field=models.CharField(choices=[('/', 'Saugmotor'), ('S', 'Kompressor'), ('C', 'Zentrifugal-Kompressor'), ('t', 'Einzelner Turbo'), ('T', 'Zwei Turbos')], help_text='If/How extra air is forced into the engine', max_length=1, null=True, verbose_name='Intake type'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='tune_characteristic',
            field=models.CharField(choices=[('S', 'Geschwindigkeit'), ('A', 'Beschleunigung'), ('a', 'Aerodynamischer Grip'), ('G', 'Grip'), ('B', 'Ausgeglichen')], default='B', help_text="What's the focus of this setup? Is it grip, or maybe speed?", max_length=1, verbose_name='Tune focus'),
        ),
        migrations.AlterField(
            model_name='fh4tune',
            name='tune_type',
            field=models.CharField(choices=[('C', 'Asphalt'), ('R', 'Rallye'), ('O', 'Offroad'), ('d', 'Drag'), ('D', 'Drift')], default='A', help_text='For what kind of racing this tune was made for', max_length=1, verbose_name='Tune type'),
        ),
    ]
