# Generated by Django 2.2.9 on 2020-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0012_auto_20200510_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fh4track',
            name='show_in_all_tracks',
            field=models.BooleanField(default=True, help_text='Show track in "FH4 Overview Page"'),
        ),
        migrations.AddField(
            model_name='fh4tune',
            name='livery_sharecode',
            field=models.IntegerField(blank=True, help_text='The Sharecode for that livery', null=True, verbose_name='Livery Sharecode'),
        ),
        migrations.AddField(
            model_name='fh4tune',
            name='tune_sharecode',
            field=models.IntegerField(blank=True, help_text='The Sharecode for that tune', null=True, verbose_name='Tune Sharecode'),
        ),
    ]
