# Generated by Django 2.2.9 on 2020-02-05 20:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('paragraphs', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True))])), ('title_and_text_with_image', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='The image below the text that scrolls by', required=True))]))])),
                ('title_image', models.ForeignKey(blank=True, help_text='Image used in the title to introduce the user to the topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Title image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
