# Generated by Django 2.2.9 on 2020-02-07 16:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendableContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('alt_title', models.CharField(blank=True, help_text='An optional alternative title differing from teh given one', max_length=200, null=True, verbose_name='Optional alternate title')),
                ('subheading', models.CharField(blank=True, help_text='A subheading that further expands on either title', max_length=200, null=True, verbose_name='Subheading')),
                ('use_both_titles', models.BooleanField(default=False, help_text='Whether both titles shall be used if both are present. If both titles are set adn this is not checked, only the secondary title will be seen.', verbose_name='Use both titles')),
                ('contents', wagtail.core.fields.StreamField([('title_and_paragraph', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True))])), ('title_and_paragraph_with_imnage', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='The image below the text that scrolls by', required=True))]))], blank=True, verbose_name='Content of teh page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('alt_title', models.CharField(blank=True, help_text='An optional alternative title differing from teh given one', max_length=200, null=True, verbose_name='Optional alternate title')),
                ('subheading', models.CharField(blank=True, help_text='A subheading that further expands on either title', max_length=200, null=True, verbose_name='Subheading')),
                ('use_both_titles', models.BooleanField(default=False, help_text='Whether both titles shall be used if both are present. If both titles are set adn this is not checked, only the secondary title will be seen.', verbose_name='Use both titles')),
                ('content', wagtail.core.fields.RichTextField(help_text='The actual textual content of this page', null=True, verbose_name='Page content')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
