# Generated by Django 2.2.9 on 2020-02-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentpages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCarousel',
        ),
    ]
