# Generated by Django 2.2.9 on 2020-05-10 20:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contentpages', '0002_delete_imagecarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendablecontentpage',
            name='contents',
            field=wagtail.core.fields.StreamField([('title_and_paragraph', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True))])), ('title_and_paragraph_with_imnage', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='The image below the text that scrolls by', required=True)), ('caption', wagtail.core.blocks.CharBlock(help_text='A caption to describe the image', max_length=500, required=False))]))], blank=True, verbose_name='Content of teh page'),
        ),
    ]
