# Generated by Django 2.2.9 on 2020-02-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('banner_title', models.CharField(help_text='The big text on the jumbotron-style banner', max_length=100, verbose_name='Banner Title')),
            ],
            options={
                'verbose_name': 'custom Homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
