# Generated by Django 2.2.9 on 2020-02-04 10:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startpage',
            options={'verbose_name': 'custom Startpage'},
        ),
        migrations.AddField(
            model_name='startpage',
            name='banner_text',
            field=wagtail.core.fields.RichTextField(default='', help_text='The main text present on the banner', verbose_name='Banner Text'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='banner_text_sub',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A possible secondary text', verbose_name='Seondary Banner Text'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='paragraphs',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True))])), ('title_and_text_with_image', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='A title for the below text', max_length=150, required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='The text for this paragraph', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='The image below the text that scrolls by', required=True))]))], blank=True),
        ),
    ]
