# Generated by Django 2.2.9 on 2020-02-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('startpage', '0002_auto_20200204_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='banner_bg_image',
            field=models.ForeignKey(blank=True, help_text='The background image behind the jumbotron banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='background image'),
        ),
        migrations.AddField(
            model_name='startpage',
            name='banner_is_bg_dark',
            field=models.BooleanField(default=False),
        ),
    ]
