# Generated by Django 2.2.9 on 2020-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_auto_20200207_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startpage',
            name='banner_is_bg_dark',
            field=models.BooleanField(default=False, help_text='Whether the background (image/solid color) is dark', verbose_name='Background dark?'),
        ),
    ]
